# Generated by Django 5.0.4 on 2024-05-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_infouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='gender',
            field=models.CharField(choices=[('S', 'sale'), ('N', 'new'), ('P', 'promotion')], max_length=100),
        ),
    ]
