# Generated by Django 5.0.4 on 2024-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_infouser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
