# Generated by Django 5.0.4 on 2024-05-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_infouser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
