# Generated by Django 5.0.6 on 2024-05-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_recentlyvieweditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyvieweditems',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
